export const FAQ = [
  { id: "add-client", title: "How do I add a client?", answer: "Open Clients and choose Add client. Enter their name and any details you have, then create the record. You can add more information later.", keywords: "new person customer roster onboarding contact email", href: "/dashboard/clients" },
  { id: "nutrition", title: "How do I calculate and save macros?", answer: "Open a client, then Nutrition targets or Stats & calculator. Enter a calorie goal, choose a preset, refine the grams and save. Protein and carbohydrates contribute 4 kcal per gram; fat contributes 9. Presets round to whole grams, so check the displayed difference.", keywords: "food diet meals eating nutrition calories kcal protein carbs fat split calculator presets", href: "/dashboard/clients" },
  { id: "weight", title: "Where do I update goals and weight?", answer: "Open a client and choose Goals for their objective, or Stats & calculator for starting, current and target weight. Progress uses the most recent check-in weight when available, with profile weight as a fallback.", keywords: "progress statistics stats kg baseline target body weight goal", href: "/dashboard/clients" },
  { id: "check-ins", title: "How do weekly check-ins work?", answer: "Open a client’s Weekly check-ins tab to record the date, weight, energy, hunger, sleep and notes. Dates must be within the past year and cannot be in the future. Saved entries appear in their progress history.", keywords: "checkin check in weekly review recovery sleep hunger energy report", href: "/dashboard/clients" },
  { id: "notifications", title: "Why does a client require attention?", answer: "Notifications lists missing setup details and check-ins that are due. Weekly check-ins are due seven days after the last entry. The dashboard counts clients needing attention once, even if they have several outstanding tasks.", keywords: "notifications alerts overdue due reminders tasks attention outstanding upcoming", href: "/dashboard/notifications" },
  { id: "notes", title: "Where can I keep coaching notes?", answer: "Open a client’s Notes tab to save context and points to follow up. Use check-in notes for observations about a particular week.", keywords: "notes comments observations context preferences", href: "/dashboard/clients" },
  { id: "planned", title: "Which features are still planned?", answer: "Workout builders, meal-plan editors and payment notifications are planned. Google sign-in, AI tools and messaging are not available. Nutrition targets and weekly check-ins can already be saved.", keywords: "workout exercises training programme meal plan payment billing invoice google ai messaging whatsapp planned", href: "/dashboard/guide" },
  { id: "tutorial", title: "Can I replay or skip the tutorial?", answer: "Use Replay tutorial on this page at any time. Finishing or skipping saves your choice to your account, so the automatic tour will not repeat on another browser or device. If saving fails, retry before closing to remember your choice.", keywords: "tutorial tour walkthrough introduction help start skip popup", href: "/dashboard/help" },
  { id: "save", title: "What if my changes will not save?", answer: "Check your internet connection and look for an error beside the save button. If your session has expired, sign in again. Keep a copy of any unsaved text before refreshing. A success message confirms a save.", keywords: "error problem connection lost login session saving failed troubleshooting", href: "/dashboard/help" },
];
export const FEATURES = [
  { id: "dashboard", title: "Dashboard", answer: "Client counts and your next actions", keywords: "home overview totals", href: "/dashboard" },
  { id: "clients", title: "Clients", answer: "Find a client and open their record", keywords: "roster people customer directory add", href: "/dashboard/clients" },
  { id: "notifications", title: "Notifications", answer: "Outstanding and upcoming tasks", keywords: "alerts attention reminders due overdue", href: "/dashboard/notifications" },
  { id: "guide", title: "Getting started", answer: "A five-step guide to the workspace", keywords: "setup onboarding guide introduction", href: "/dashboard/guide" },
  { id: "help", title: "Help & FAQ", answer: "Answers and tutorial replay", keywords: "support question tutorial tour", href: "/dashboard/help" },
];
export function searchHelp(query: string) {
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  const entries = [...FEATURES.map(item => ({ ...item, kind: "Feature" })), ...FAQ.map(item => ({ ...item, href: `/dashboard/help#${item.id}`, kind: "Answer" }))];
  if (!words.length) return entries.filter(item => item.kind === "Feature");
  return entries.map(item => ({ item, score: words.reduce((sum, word) => sum + (item.title.toLowerCase().includes(word) ? 4 : `${item.keywords} ${item.answer}`.toLowerCase().includes(word) ? 1 : 0), 0) })).filter(result => result.score > 0).sort((a,b) => b.score-a.score).slice(0,8).map(result => result.item);
}
